### ISSUE TITLE
Is this meant to replace standard roles in bolt4?

### ISSUE THREAD

**Issue by marck-consulting** [bolt/users#6]
Is this extension meant to be used as a replacement of the standard roles or in addition to them?
Since I can only assign one role per user I'm not really sure how to deal with the roles ROLE_ADMIN, ROLE_EDITOR and ROLE_USER after setting up the extension.

**Comment by I-Valchev** [comment]
hi @marck-consulting ,

So far this is meant to help you implement frontend users. Those roles work _in addition_ to the standard ones, but strictly speaking they should not affect each other.

In Bolt itself, for now only the `ROLE_ADMIN` role is used to grant access to the backend. The other roles exist, but Bolt itself does not use them for anything (yet).

Does that answer your question? If you prefer, you can reach me on Bolt's Slack as well for faster replies.

**Comment by marck-consulting** [comment]
Sure, just closing it and getting in touch via slack.
